sudo: required

dist: trusty

services:
  - docker

language: node_js

node_js:
  - "8"

env:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

cache: npm

script:
  - set -e && make build

deploy:
  provider: script
  script: bash deploy-docker.sh
  on:
    branch: master


